import pandas as pd
import matplotlib.pyplot as plt
df = pd.read_csv("superstore.csv")
print(df.head())
print("\nDataset Shape:")
print(df.shape)

print("\nColumn Names:")
print(df.columns)

print("\nDataset Information:")
df.info()
print("\nMissing Values:")
print(df.isnull().sum())

print("\nDuplicate Rows:")
print(df.duplicated().sum())
print("\n--- SALES SUMMARY ---")

print("Total Sales:", df["Sales"].sum())
print("Total Profit:", df["Profit"].sum())
print("Total Quantity Sold:", df["Quantity"].sum())

print("\nSales by Category:")
print(df.groupby("Category")["Sales"].sum())
category_sales = df.groupby("Category")["Sales"].sum()

category_sales.plot(kind="bar")

plt.title("Sales by Category")
plt.xlabel("Category")
plt.ylabel("Total Sales")
plt.xticks(rotation=0)
plt.tight_layout()
plt.savefig("sales_by_category.png", dpi=300, bbox_inches="tight")
plt.show()
print("\nProfit by Category:")
profit_by_category = df.groupby("Category")["Profit"].sum().sort_values()
print(profit_by_category)

profit_by_category.plot(kind="bar", color="seagreen")
plt.title("Profit by Category")
plt.xlabel("Category")
plt.ylabel("Total Profit")
plt.xticks(rotation=0)
plt.tight_layout()
plt.savefig("profit_by_category.png", dpi=300, bbox_inches="tight")
plt.show()

print("\nProfit by Region:")
profit_by_region = df.groupby("Region")["Profit"].sum().sort_values()
print(profit_by_region)

profit_by_region.plot(kind="barh", color="cornflowerblue")
plt.title("Profit by Region")
plt.xlabel("Total Profit")
plt.ylabel("Region")
plt.tight_layout()
plt.savefig("profit_by_region.png", dpi=300, bbox_inches="tight")
plt.show()

df["Order Date"] = pd.to_datetime(df["Order Date"], dayfirst=True)
monthly_sales = df.resample("MS", on="Order Date")["Sales"].sum()
print("\nMonthly Sales:")
print(monthly_sales)

monthly_sales.plot(kind="line", marker="o", figsize=(10, 5))
plt.title("Monthly Sales Trend")
plt.xlabel("Month")
plt.ylabel("Total Sales")
plt.grid(True, alpha=0.3)
plt.tight_layout()
plt.savefig("monthly_sales_trend.png", dpi=300, bbox_inches="tight")
plt.show()

print("\nTop 10 Products by Sales:")
top_products = df.groupby("Product Name")["Sales"].sum().nlargest(10).sort_values()
print(top_products.sort_values(ascending=False))

plt.figure(figsize=(10, 6))
plt.barh(top_products.index, top_products.values, color="darkorange")
plt.title("Top 10 Products by Sales")
plt.xlabel("Total Sales")
plt.ylabel("Product")
plt.tight_layout()
plt.savefig("top_10_products.png", dpi=300, bbox_inches="tight")
plt.show()
